# MySQL Database Configuration

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbr_db
    username: root
    password: Vishal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
         ddl-auto: update
         format_sql: true
         
server:
  port: 8080
